# Generated by Django 4.2.1 on 2023-06-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_booking_options_bookinguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
